spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/car-rest-service}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1111}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-4bh6bh3loibqhi5o.eu.auth0.com/
          jwk-set-uri: https://dev-4bh6bh3loibqhi5o.eu.auth0.com/.well-known/jwks.json
          audiences: http://car-rest-service.com
auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}