spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
          jwk-set-uri: https://${AUTH0_DOMAIN}/.well-known/jwks.json
          audiences: ${AUTH0_AUDIENCE}

springdoc:
  swagger-ui:
    path: /openapi

server:
  error:
    include-binding-errors: always
    include-message: always

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}
