spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/car-rest-service
    username: admin
    password: 1111
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-4bh6bh3loibqhi5o.eu.auth0.com/
          jwk-set-uri: https://dev-4bh6bh3loibqhi5o.eu.auth0.com/.well-known/jwks.json
          audiences: http://car-rest-service.com

springdoc:
  swagger-ui:
    path: /openapi

server:
  error:
    include-binding-errors: always
    include-message: always

auth0:
  domain: dev-4bh6bh3loibqhi5o.eu.auth0.com
  clientId: iSnXUswhEkfa1YWgGCpcLSsF7k3Hdv1s
  clientSecret: 9XgmrWCRz9lPZ_vTNOp5rzQHPBcOQQtpy-mIf-UEekQvcSEl2d4VQ6yUuWI6ykTf
  audience: http://car-rest-service.com

logging:
  level:
    org:
      springframework:
        security: ERROR